[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "/*.html"
  [headers.defaults]
  Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/images/*"
  [headers.defaults]
  Cache-Control = "public, max-age=31536000"
